[theme]
base = "light"
primaryColor = "#4CAF50"         # green
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#E8F5E9"
textColor = "#262730"
font = "sans serif"              # Options: "sans serif", "serif", "monospace"

[server]
headless = true
runOnSave = true